language: r
cache: packages
r_packages:
  - plotly
  - shiny
  - ggplot2
  - stringr
  - readr
  - haven
  - readxl
  - RColorBrewer
  - covr
r_github_packages:
  - NCEAS/metajam
warnings_are_errors: false
after_success:
  - Rscript -e 'library(covr); codecov()'
  