---
title: "`r report_title`"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output:
  html_document:
    toc: true
    toc_depth: 4
---

```{r echo = F}
knitr::opts_chunk$set(comment=NA, echo = F, message = F, warning = F, out.width = '100%', fig.height = 4)
```

---

&nbsp;

## Overall data table report

```{r echo = F}
kable(entity_report[["all"]],
      col.names = c("Variable", "Class", "No. Values", "No. NAs"),
      row.names = F)

```

&nbsp;

#### Summary of numerical variables

```{r echo=FALSE}
if (nrow(entity_report[["numvars"]]) > 0) {
   kable(
      as.data.frame(entity_report[["numvars"]]),
      digits = 2,
      align = "l",
      col.names = c(
         "Variable",
         "Min",
         "1st qu.",
         "2nd qu.",
         "3rd qu.",
         "Max",
         "Mean",
         "No. unique"
      )
   )
} else {
   print("No numerical variables found.")
}
```

&nbsp;

#### Summary of categorical variables

```{r}
if (!is.null(entity_report[["catvars"]]) ) {
   kable(entity_report[["catvars"]][[1]],
         align = "l",
         col.names = c("Variable",
                       "No. levels"
         ))
   
   entity_report[["catvars"]][[2]]
} else {
   print("No categorical/character variables found.")
}
```

<!-- &nbsp; -->

<!-- #### Levels in categorical variables -->

<!-- ```{r} -->
<!-- if (!is.null(entity_report[["levels"]])) { -->
<!-- kable(entity_report[["levels"]], -->
<!--       align = 'l', -->
<!--       col.names = c("Variable", -->
<!--                     "Level", -->
<!--                     "No. values", -->
<!--                     "No. NAs")) -->
<!-- } else { -->
<!--   print("No categorical/character variables found.") -->
<!-- } -->
<!-- ``` -->

&nbsp;


---

## Temporal information


---

## Spatial information

```{r}
xy <- datapie::space_detective(entity_list)
```


---

&nbsp;

## Variable-by-variable Report

```{r results='asis'}
for (i in 1:length(var_report)) {
   cat('\n')
   cat('\n')
   cat(paste("### Variable:", var_report[[i]][["var_name"]]))
   cat('\n')
   print(var_report[[i]][["plots"]][["x"]])
   cat('\n')
   # if (!is.null(var_report[[i]][["missing"]])) {
   #    print(var_report[[i]][["missing"]])
   #    cat('\n')
   # }
   if (!is.null(var_report[[i]][["space"]])) {
      print(var_report[[i]][["space"]][[1]])
      cat('\n')
      if (!is.null(var_report[[i]][["space"]][[2]])) {
         print(var_report[[i]][["space"]][[2]])
         cat('\n')
      }
   }
}
```