---
title: "`r report_title`"
author: "Generated by R package `datapie`"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output:
  html_document:
    toc: true
    toc_depth: 4
    toc_float: true
---

```{r echo = F}
knitr::opts_chunk$set(comment=NA, echo = F, message = F, warning = F, out.width = '100%', fig.height = 3)
```

---

&nbsp;

## Overall data table report

&nbsp;

#### Summary of numerical variables

```{r echo=FALSE}
if (nrow(entity_report[["numvars"]]) > 0) {
   kable(
      as.data.frame(entity_report[["numvars"]]),
      digits = 2,
      align = "l",
      col.names = c(
         "Variable",
         "Min",
         "1st qu.",
         "2nd qu.",
         "3rd qu.",
         "Max",
         "Mean",
         "No. unique",
         "No. values",
         "No. NAs"
      )
   )
} else {
   print("No numerical variables found.")
}
```

&nbsp;

#### Summary of categorical variables

```{r}
if (nrow(entity_report[["catvars"]]) > 0) {
   kable(entity_report[["catvars"]],
         align = "l",
         col.names = c("Variable",
                       "No. values",
                       "No. levels",
                       "No. NAs"))
} else {
   print("No categorical/character variables found.")
}
```

&nbsp;

#### Levels in categorical variables

```{r}
if (nrow(entity_report[["levels"]]) > 0) {
kable(entity_report[["levels"]],
      align = 'l',
      col.names = c("Variable",
                    "Level",
                    "No. values",
                    "No. NAs"))
} else {
  print("No categorical/character variables found.")
}
```

&nbsp;


---

## Temporal information


---

## Spatial information

```{r}
xy <- space_detective(entity_list)
```


---

&nbsp;

## Variable-by-variable Report

```{r results='asis'}
for (i in 1:length(var_report)) {
   cat('\n')
   cat('\n')
   cat(paste("### Variable:", var_report[[i]][["var_name"]]))
   cat('\n')
   print(var_report[[i]][["plots"]][["x"]])
   cat('\n')
   if (!is.null(var_report[[i]][["missing"]])) {
      print(var_report[[i]][["missing"]])
      cat('\n')
   }
   if (!is.null(var_report[[i]][["space"]])) {
      print(var_report[[i]][["space"]][[1]])
      cat('\n')
      print(var_report[[i]][["space"]][[2]])
      cat('\n')
   }
}
```